-- CREATE DATABASE
CREATE DATABASE OLEAGUE;
CREATE DATABASE OLEAGUE CHARACTER SET utf8 COLLATE utf8_general_ci;

-- DELETE DATABASE
DROP DATABASE OLEAGUE;

-- USE DATABASE
USE OLEAGUE

-- CREATE TABLE
CREATE TABLE MATCHES (
  MATCH_ID INTEGER NOT NULL,
  TEAM_ID INTEGER NOT NULL,
  PLAYER_ID INTEGER NOT NULL,
  WON SMALLINT NOT NULL,
  LOST SMALLINT NOT NULL,
  PRIMARY KEY (MATCH_ID)
);

CREATE TABLE MEMBERS (
  PLAYER_ID INTEGER NOT NULL,
  EFFECTIVE_DATE DATE NOT NULL,
  EXPIRED_DATE DATE DEFAULT NULL,
  POSITION CHAR(20) DEFAULT NULL,
  PRIMARY KEY (PLAYER_ID, EFFECTIVE_DATE)
);

CREATE TABLE PAYMENTS (
  PAYMENT_ID INTEGER NOT NULL,
  PLAYER_ID INTEGER NOT NULL,
  PAYMENT_DATE DATE NOT NULL,
  AMOUNT DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (PAYMENT_ID)
);

CREATE TABLE PLAYERS (
  PLAYER_ID INTEGER NOT NULL,
  FIRSTNAME CHAR(50) NOT NULL,
  LASTNAME CHAR(50) NOT NULL,
  BIRTH_DATE  DATE DEFAULT NULL,
  SEX CHAR(1) NOT NULL,
  JOINED SMALLINT NOT NULL,
  HOUSE_NO CHAR(50) DEFAULT NULL,
  STREET VARCHAR(100) NOT NULL,
  DISTRICT VARCHAR(100) DEFAULT NULL,
  AMPHUR VARCHAR(100) DEFAULT NULL,
  CITY VARCHAR(100) NOT NULL,
  ZIPCODE CHAR(10) DEFAULT NULL,
  TEL CHAR(20) DEFAULT NULL,
  LEAGUE_ID CHAR(4) DEFAULT NULL,
  PRIMARY KEY (PLAYER_ID)
);

CREATE TABLE TEAMS (
  TEAM_ID INTEGER NOT NULL,
  PLAYER_ID INTEGER NOT NULL,
  DIVISION CHAR(20) NOT NULL,
  PRIMARY KEY (TEAM_ID)
);
